main: main.c string_utilities.c string_utilities.h
	gcc -o string_utilities main.c string_utilities.c string_utilities.h
ws: main2.c string_utilities.c string_utilities.h
	gcc -o ws main2.c string_utilities.c string_utilities.h