#!/bin/bash

#compares 2 strings and prints which is smaller in lexicographical order

if [[ $1 = $2 || $# != 2 ]] # checks if arguments are the same or the number or arguments is not valid
then
	echo "Error! Please enter 2 different arguments." >&2
	exit 1
elif [[ $1 < $2 ]]
then
	echo "$1 is smaller than $2"
	exit 0
else
	echo "$2 is smaller than $1"
	exit 0
fi
