#!/bin/bash

#prints the smaller of 2 integers passed as arguments

if [[ $1 -eq $2 || $# != 2 ]] # checks is the number of arguments dosen't equal 2 
                              # or checks if the arguments are equal value: then returns error
then
	echo "Error! Please enter 2 different integers." >&2
	exit 1
elif [[ $1 -lt $2 ]]
then
	echo "$1 is smaller than $2"
	exit 0
else
	echo "$2 is smaller than $1"
	exit 0
fi
