#!/bin/bash
if [[ $1 -eq $2 || $# != 2 ]]
then
	echo "Error! Please enter 2 different integers." >&2
	exit 1
elif [[ $1 -lt $2 ]]
then
	echo "$1 is smaller than $2"
	exit 0
else
	echo "$2 is smaller than $1"
	exit 0
fi
